// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package db_mock

import (
	"context"
	"github.com/TheEdgeOfRage/ytrssil-api/db"
	"github.com/TheEdgeOfRage/ytrssil-api/models"
	"sync"
	"time"
)

// Ensure, that DBMock does implement db.DB.
// If this is not the case, regenerate this file with moq.
var _ db.DB = &DBMock{}

// DBMock is a mock implementation of db.DB.
//
//	func TestSomethingThatUsesDB(t *testing.T) {
//
//		// make and configure a mocked db.DB
//		mockedDB := &DBMock{
//			AddVideoFunc: func(ctx context.Context, video models.Video, channelID string) error {
//				panic("mock out the AddVideo method")
//			},
//			CloseFunc: func()  {
//				panic("mock out the Close method")
//			},
//			DeleteVideoFileFunc: func(ctx context.Context, videoID string) error {
//				panic("mock out the DeleteVideoFile method")
//			},
//			GetNewVideosFunc: func(ctx context.Context, sortDesc bool) ([]models.Video, error) {
//				panic("mock out the GetNewVideos method")
//			},
//			GetVideoFunc: func(ctx context.Context, videoID string) (*models.Video, error) {
//				panic("mock out the GetVideo method")
//			},
//			GetVideosForCleanupFunc: func(ctx context.Context, olderThan time.Duration) ([]models.Video, error) {
//				panic("mock out the GetVideosForCleanup method")
//			},
//			GetWatchedVideosFunc: func(ctx context.Context, sortDesc bool, limit int, offset int) ([]models.Video, error) {
//				panic("mock out the GetWatchedVideos method")
//			},
//			HasVideoFunc: func(ctx context.Context, videoID string) (bool, error) {
//				panic("mock out the HasVideo method")
//			},
//			ListChannelsFunc: func(ctx context.Context) ([]models.Channel, error) {
//				panic("mock out the ListChannels method")
//			},
//			SetVideoDownloadCompletedFunc: func(ctx context.Context, videoID string, filePath string) error {
//				panic("mock out the SetVideoDownloadCompleted method")
//			},
//			SetVideoDownloadFailedFunc: func(ctx context.Context, videoID string, errorMsg string) error {
//				panic("mock out the SetVideoDownloadFailed method")
//			},
//			SetVideoDownloadStatusFunc: func(ctx context.Context, videoID string, status string) error {
//				panic("mock out the SetVideoDownloadStatus method")
//			},
//			SetVideoProgressFunc: func(ctx context.Context, videoID string, progress int) (*models.Video, error) {
//				panic("mock out the SetVideoProgress method")
//			},
//			SetVideoWatchTimeFunc: func(ctx context.Context, videoID string, watchTime *time.Time) error {
//				panic("mock out the SetVideoWatchTime method")
//			},
//			SubscribeToChannelFunc: func(ctx context.Context, channel models.Channel) error {
//				panic("mock out the SubscribeToChannel method")
//			},
//			UnsubscribeFromChannelFunc: func(ctx context.Context, channelID string) error {
//				panic("mock out the UnsubscribeFromChannel method")
//			},
//		}
//
//		// use mockedDB in code that requires db.DB
//		// and then make assertions.
//
//	}
type DBMock struct {
	// AddVideoFunc mocks the AddVideo method.
	AddVideoFunc func(ctx context.Context, video models.Video, channelID string) error

	// CloseFunc mocks the Close method.
	CloseFunc func()

	// DeleteVideoFileFunc mocks the DeleteVideoFile method.
	DeleteVideoFileFunc func(ctx context.Context, videoID string) error

	// GetNewVideosFunc mocks the GetNewVideos method.
	GetNewVideosFunc func(ctx context.Context, sortDesc bool) ([]models.Video, error)

	// GetVideoFunc mocks the GetVideo method.
	GetVideoFunc func(ctx context.Context, videoID string) (*models.Video, error)

	// GetVideosForCleanupFunc mocks the GetVideosForCleanup method.
	GetVideosForCleanupFunc func(ctx context.Context, olderThan time.Duration) ([]models.Video, error)

	// GetWatchedVideosFunc mocks the GetWatchedVideos method.
	GetWatchedVideosFunc func(ctx context.Context, sortDesc bool, limit int, offset int) ([]models.Video, error)

	// HasVideoFunc mocks the HasVideo method.
	HasVideoFunc func(ctx context.Context, videoID string) (bool, error)

	// ListChannelsFunc mocks the ListChannels method.
	ListChannelsFunc func(ctx context.Context) ([]models.Channel, error)

	// SetVideoDownloadCompletedFunc mocks the SetVideoDownloadCompleted method.
	SetVideoDownloadCompletedFunc func(ctx context.Context, videoID string, filePath string) error

	// SetVideoDownloadFailedFunc mocks the SetVideoDownloadFailed method.
	SetVideoDownloadFailedFunc func(ctx context.Context, videoID string, errorMsg string) error

	// SetVideoDownloadStatusFunc mocks the SetVideoDownloadStatus method.
	SetVideoDownloadStatusFunc func(ctx context.Context, videoID string, status string) error

	// SetVideoProgressFunc mocks the SetVideoProgress method.
	SetVideoProgressFunc func(ctx context.Context, videoID string, progress int) (*models.Video, error)

	// SetVideoWatchTimeFunc mocks the SetVideoWatchTime method.
	SetVideoWatchTimeFunc func(ctx context.Context, videoID string, watchTime *time.Time) error

	// SubscribeToChannelFunc mocks the SubscribeToChannel method.
	SubscribeToChannelFunc func(ctx context.Context, channel models.Channel) error

	// UnsubscribeFromChannelFunc mocks the UnsubscribeFromChannel method.
	UnsubscribeFromChannelFunc func(ctx context.Context, channelID string) error

	// calls tracks calls to the methods.
	calls struct {
		// AddVideo holds details about calls to the AddVideo method.
		AddVideo []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Video is the video argument value.
			Video models.Video
			// ChannelID is the channelID argument value.
			ChannelID string
		}
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// DeleteVideoFile holds details about calls to the DeleteVideoFile method.
		DeleteVideoFile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// VideoID is the videoID argument value.
			VideoID string
		}
		// GetNewVideos holds details about calls to the GetNewVideos method.
		GetNewVideos []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SortDesc is the sortDesc argument value.
			SortDesc bool
		}
		// GetVideo holds details about calls to the GetVideo method.
		GetVideo []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// VideoID is the videoID argument value.
			VideoID string
		}
		// GetVideosForCleanup holds details about calls to the GetVideosForCleanup method.
		GetVideosForCleanup []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OlderThan is the olderThan argument value.
			OlderThan time.Duration
		}
		// GetWatchedVideos holds details about calls to the GetWatchedVideos method.
		GetWatchedVideos []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SortDesc is the sortDesc argument value.
			SortDesc bool
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// HasVideo holds details about calls to the HasVideo method.
		HasVideo []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// VideoID is the videoID argument value.
			VideoID string
		}
		// ListChannels holds details about calls to the ListChannels method.
		ListChannels []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// SetVideoDownloadCompleted holds details about calls to the SetVideoDownloadCompleted method.
		SetVideoDownloadCompleted []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// VideoID is the videoID argument value.
			VideoID string
			// FilePath is the filePath argument value.
			FilePath string
		}
		// SetVideoDownloadFailed holds details about calls to the SetVideoDownloadFailed method.
		SetVideoDownloadFailed []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// VideoID is the videoID argument value.
			VideoID string
			// ErrorMsg is the errorMsg argument value.
			ErrorMsg string
		}
		// SetVideoDownloadStatus holds details about calls to the SetVideoDownloadStatus method.
		SetVideoDownloadStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// VideoID is the videoID argument value.
			VideoID string
			// Status is the status argument value.
			Status string
		}
		// SetVideoProgress holds details about calls to the SetVideoProgress method.
		SetVideoProgress []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// VideoID is the videoID argument value.
			VideoID string
			// Progress is the progress argument value.
			Progress int
		}
		// SetVideoWatchTime holds details about calls to the SetVideoWatchTime method.
		SetVideoWatchTime []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// VideoID is the videoID argument value.
			VideoID string
			// WatchTime is the watchTime argument value.
			WatchTime *time.Time
		}
		// SubscribeToChannel holds details about calls to the SubscribeToChannel method.
		SubscribeToChannel []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Channel is the channel argument value.
			Channel models.Channel
		}
		// UnsubscribeFromChannel holds details about calls to the UnsubscribeFromChannel method.
		UnsubscribeFromChannel []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChannelID is the channelID argument value.
			ChannelID string
		}
	}
	lockAddVideo                  sync.RWMutex
	lockClose                     sync.RWMutex
	lockDeleteVideoFile           sync.RWMutex
	lockGetNewVideos              sync.RWMutex
	lockGetVideo                  sync.RWMutex
	lockGetVideosForCleanup       sync.RWMutex
	lockGetWatchedVideos          sync.RWMutex
	lockHasVideo                  sync.RWMutex
	lockListChannels              sync.RWMutex
	lockSetVideoDownloadCompleted sync.RWMutex
	lockSetVideoDownloadFailed    sync.RWMutex
	lockSetVideoDownloadStatus    sync.RWMutex
	lockSetVideoProgress          sync.RWMutex
	lockSetVideoWatchTime         sync.RWMutex
	lockSubscribeToChannel        sync.RWMutex
	lockUnsubscribeFromChannel    sync.RWMutex
}

// AddVideo calls AddVideoFunc.
func (mock *DBMock) AddVideo(ctx context.Context, video models.Video, channelID string) error {
	if mock.AddVideoFunc == nil {
		panic("DBMock.AddVideoFunc: method is nil but DB.AddVideo was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Video     models.Video
		ChannelID string
	}{
		Ctx:       ctx,
		Video:     video,
		ChannelID: channelID,
	}
	mock.lockAddVideo.Lock()
	mock.calls.AddVideo = append(mock.calls.AddVideo, callInfo)
	mock.lockAddVideo.Unlock()
	return mock.AddVideoFunc(ctx, video, channelID)
}

// AddVideoCalls gets all the calls that were made to AddVideo.
// Check the length with:
//
//	len(mockedDB.AddVideoCalls())
func (mock *DBMock) AddVideoCalls() []struct {
	Ctx       context.Context
	Video     models.Video
	ChannelID string
} {
	var calls []struct {
		Ctx       context.Context
		Video     models.Video
		ChannelID string
	}
	mock.lockAddVideo.RLock()
	calls = mock.calls.AddVideo
	mock.lockAddVideo.RUnlock()
	return calls
}

// Close calls CloseFunc.
func (mock *DBMock) Close() {
	if mock.CloseFunc == nil {
		panic("DBMock.CloseFunc: method is nil but DB.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedDB.CloseCalls())
func (mock *DBMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// DeleteVideoFile calls DeleteVideoFileFunc.
func (mock *DBMock) DeleteVideoFile(ctx context.Context, videoID string) error {
	if mock.DeleteVideoFileFunc == nil {
		panic("DBMock.DeleteVideoFileFunc: method is nil but DB.DeleteVideoFile was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		VideoID string
	}{
		Ctx:     ctx,
		VideoID: videoID,
	}
	mock.lockDeleteVideoFile.Lock()
	mock.calls.DeleteVideoFile = append(mock.calls.DeleteVideoFile, callInfo)
	mock.lockDeleteVideoFile.Unlock()
	return mock.DeleteVideoFileFunc(ctx, videoID)
}

// DeleteVideoFileCalls gets all the calls that were made to DeleteVideoFile.
// Check the length with:
//
//	len(mockedDB.DeleteVideoFileCalls())
func (mock *DBMock) DeleteVideoFileCalls() []struct {
	Ctx     context.Context
	VideoID string
} {
	var calls []struct {
		Ctx     context.Context
		VideoID string
	}
	mock.lockDeleteVideoFile.RLock()
	calls = mock.calls.DeleteVideoFile
	mock.lockDeleteVideoFile.RUnlock()
	return calls
}

// GetNewVideos calls GetNewVideosFunc.
func (mock *DBMock) GetNewVideos(ctx context.Context, sortDesc bool) ([]models.Video, error) {
	if mock.GetNewVideosFunc == nil {
		panic("DBMock.GetNewVideosFunc: method is nil but DB.GetNewVideos was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		SortDesc bool
	}{
		Ctx:      ctx,
		SortDesc: sortDesc,
	}
	mock.lockGetNewVideos.Lock()
	mock.calls.GetNewVideos = append(mock.calls.GetNewVideos, callInfo)
	mock.lockGetNewVideos.Unlock()
	return mock.GetNewVideosFunc(ctx, sortDesc)
}

// GetNewVideosCalls gets all the calls that were made to GetNewVideos.
// Check the length with:
//
//	len(mockedDB.GetNewVideosCalls())
func (mock *DBMock) GetNewVideosCalls() []struct {
	Ctx      context.Context
	SortDesc bool
} {
	var calls []struct {
		Ctx      context.Context
		SortDesc bool
	}
	mock.lockGetNewVideos.RLock()
	calls = mock.calls.GetNewVideos
	mock.lockGetNewVideos.RUnlock()
	return calls
}

// GetVideo calls GetVideoFunc.
func (mock *DBMock) GetVideo(ctx context.Context, videoID string) (*models.Video, error) {
	if mock.GetVideoFunc == nil {
		panic("DBMock.GetVideoFunc: method is nil but DB.GetVideo was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		VideoID string
	}{
		Ctx:     ctx,
		VideoID: videoID,
	}
	mock.lockGetVideo.Lock()
	mock.calls.GetVideo = append(mock.calls.GetVideo, callInfo)
	mock.lockGetVideo.Unlock()
	return mock.GetVideoFunc(ctx, videoID)
}

// GetVideoCalls gets all the calls that were made to GetVideo.
// Check the length with:
//
//	len(mockedDB.GetVideoCalls())
func (mock *DBMock) GetVideoCalls() []struct {
	Ctx     context.Context
	VideoID string
} {
	var calls []struct {
		Ctx     context.Context
		VideoID string
	}
	mock.lockGetVideo.RLock()
	calls = mock.calls.GetVideo
	mock.lockGetVideo.RUnlock()
	return calls
}

// GetVideosForCleanup calls GetVideosForCleanupFunc.
func (mock *DBMock) GetVideosForCleanup(ctx context.Context, olderThan time.Duration) ([]models.Video, error) {
	if mock.GetVideosForCleanupFunc == nil {
		panic("DBMock.GetVideosForCleanupFunc: method is nil but DB.GetVideosForCleanup was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		OlderThan time.Duration
	}{
		Ctx:       ctx,
		OlderThan: olderThan,
	}
	mock.lockGetVideosForCleanup.Lock()
	mock.calls.GetVideosForCleanup = append(mock.calls.GetVideosForCleanup, callInfo)
	mock.lockGetVideosForCleanup.Unlock()
	return mock.GetVideosForCleanupFunc(ctx, olderThan)
}

// GetVideosForCleanupCalls gets all the calls that were made to GetVideosForCleanup.
// Check the length with:
//
//	len(mockedDB.GetVideosForCleanupCalls())
func (mock *DBMock) GetVideosForCleanupCalls() []struct {
	Ctx       context.Context
	OlderThan time.Duration
} {
	var calls []struct {
		Ctx       context.Context
		OlderThan time.Duration
	}
	mock.lockGetVideosForCleanup.RLock()
	calls = mock.calls.GetVideosForCleanup
	mock.lockGetVideosForCleanup.RUnlock()
	return calls
}

// GetWatchedVideos calls GetWatchedVideosFunc.
func (mock *DBMock) GetWatchedVideos(ctx context.Context, sortDesc bool, limit int, offset int) ([]models.Video, error) {
	if mock.GetWatchedVideosFunc == nil {
		panic("DBMock.GetWatchedVideosFunc: method is nil but DB.GetWatchedVideos was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		SortDesc bool
		Limit    int
		Offset   int
	}{
		Ctx:      ctx,
		SortDesc: sortDesc,
		Limit:    limit,
		Offset:   offset,
	}
	mock.lockGetWatchedVideos.Lock()
	mock.calls.GetWatchedVideos = append(mock.calls.GetWatchedVideos, callInfo)
	mock.lockGetWatchedVideos.Unlock()
	return mock.GetWatchedVideosFunc(ctx, sortDesc, limit, offset)
}

// GetWatchedVideosCalls gets all the calls that were made to GetWatchedVideos.
// Check the length with:
//
//	len(mockedDB.GetWatchedVideosCalls())
func (mock *DBMock) GetWatchedVideosCalls() []struct {
	Ctx      context.Context
	SortDesc bool
	Limit    int
	Offset   int
} {
	var calls []struct {
		Ctx      context.Context
		SortDesc bool
		Limit    int
		Offset   int
	}
	mock.lockGetWatchedVideos.RLock()
	calls = mock.calls.GetWatchedVideos
	mock.lockGetWatchedVideos.RUnlock()
	return calls
}

// HasVideo calls HasVideoFunc.
func (mock *DBMock) HasVideo(ctx context.Context, videoID string) (bool, error) {
	if mock.HasVideoFunc == nil {
		panic("DBMock.HasVideoFunc: method is nil but DB.HasVideo was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		VideoID string
	}{
		Ctx:     ctx,
		VideoID: videoID,
	}
	mock.lockHasVideo.Lock()
	mock.calls.HasVideo = append(mock.calls.HasVideo, callInfo)
	mock.lockHasVideo.Unlock()
	return mock.HasVideoFunc(ctx, videoID)
}

// HasVideoCalls gets all the calls that were made to HasVideo.
// Check the length with:
//
//	len(mockedDB.HasVideoCalls())
func (mock *DBMock) HasVideoCalls() []struct {
	Ctx     context.Context
	VideoID string
} {
	var calls []struct {
		Ctx     context.Context
		VideoID string
	}
	mock.lockHasVideo.RLock()
	calls = mock.calls.HasVideo
	mock.lockHasVideo.RUnlock()
	return calls
}

// ListChannels calls ListChannelsFunc.
func (mock *DBMock) ListChannels(ctx context.Context) ([]models.Channel, error) {
	if mock.ListChannelsFunc == nil {
		panic("DBMock.ListChannelsFunc: method is nil but DB.ListChannels was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListChannels.Lock()
	mock.calls.ListChannels = append(mock.calls.ListChannels, callInfo)
	mock.lockListChannels.Unlock()
	return mock.ListChannelsFunc(ctx)
}

// ListChannelsCalls gets all the calls that were made to ListChannels.
// Check the length with:
//
//	len(mockedDB.ListChannelsCalls())
func (mock *DBMock) ListChannelsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListChannels.RLock()
	calls = mock.calls.ListChannels
	mock.lockListChannels.RUnlock()
	return calls
}

// SetVideoDownloadCompleted calls SetVideoDownloadCompletedFunc.
func (mock *DBMock) SetVideoDownloadCompleted(ctx context.Context, videoID string, filePath string) error {
	if mock.SetVideoDownloadCompletedFunc == nil {
		panic("DBMock.SetVideoDownloadCompletedFunc: method is nil but DB.SetVideoDownloadCompleted was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		VideoID  string
		FilePath string
	}{
		Ctx:      ctx,
		VideoID:  videoID,
		FilePath: filePath,
	}
	mock.lockSetVideoDownloadCompleted.Lock()
	mock.calls.SetVideoDownloadCompleted = append(mock.calls.SetVideoDownloadCompleted, callInfo)
	mock.lockSetVideoDownloadCompleted.Unlock()
	return mock.SetVideoDownloadCompletedFunc(ctx, videoID, filePath)
}

// SetVideoDownloadCompletedCalls gets all the calls that were made to SetVideoDownloadCompleted.
// Check the length with:
//
//	len(mockedDB.SetVideoDownloadCompletedCalls())
func (mock *DBMock) SetVideoDownloadCompletedCalls() []struct {
	Ctx      context.Context
	VideoID  string
	FilePath string
} {
	var calls []struct {
		Ctx      context.Context
		VideoID  string
		FilePath string
	}
	mock.lockSetVideoDownloadCompleted.RLock()
	calls = mock.calls.SetVideoDownloadCompleted
	mock.lockSetVideoDownloadCompleted.RUnlock()
	return calls
}

// SetVideoDownloadFailed calls SetVideoDownloadFailedFunc.
func (mock *DBMock) SetVideoDownloadFailed(ctx context.Context, videoID string, errorMsg string) error {
	if mock.SetVideoDownloadFailedFunc == nil {
		panic("DBMock.SetVideoDownloadFailedFunc: method is nil but DB.SetVideoDownloadFailed was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		VideoID  string
		ErrorMsg string
	}{
		Ctx:      ctx,
		VideoID:  videoID,
		ErrorMsg: errorMsg,
	}
	mock.lockSetVideoDownloadFailed.Lock()
	mock.calls.SetVideoDownloadFailed = append(mock.calls.SetVideoDownloadFailed, callInfo)
	mock.lockSetVideoDownloadFailed.Unlock()
	return mock.SetVideoDownloadFailedFunc(ctx, videoID, errorMsg)
}

// SetVideoDownloadFailedCalls gets all the calls that were made to SetVideoDownloadFailed.
// Check the length with:
//
//	len(mockedDB.SetVideoDownloadFailedCalls())
func (mock *DBMock) SetVideoDownloadFailedCalls() []struct {
	Ctx      context.Context
	VideoID  string
	ErrorMsg string
} {
	var calls []struct {
		Ctx      context.Context
		VideoID  string
		ErrorMsg string
	}
	mock.lockSetVideoDownloadFailed.RLock()
	calls = mock.calls.SetVideoDownloadFailed
	mock.lockSetVideoDownloadFailed.RUnlock()
	return calls
}

// SetVideoDownloadStatus calls SetVideoDownloadStatusFunc.
func (mock *DBMock) SetVideoDownloadStatus(ctx context.Context, videoID string, status string) error {
	if mock.SetVideoDownloadStatusFunc == nil {
		panic("DBMock.SetVideoDownloadStatusFunc: method is nil but DB.SetVideoDownloadStatus was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		VideoID string
		Status  string
	}{
		Ctx:     ctx,
		VideoID: videoID,
		Status:  status,
	}
	mock.lockSetVideoDownloadStatus.Lock()
	mock.calls.SetVideoDownloadStatus = append(mock.calls.SetVideoDownloadStatus, callInfo)
	mock.lockSetVideoDownloadStatus.Unlock()
	return mock.SetVideoDownloadStatusFunc(ctx, videoID, status)
}

// SetVideoDownloadStatusCalls gets all the calls that were made to SetVideoDownloadStatus.
// Check the length with:
//
//	len(mockedDB.SetVideoDownloadStatusCalls())
func (mock *DBMock) SetVideoDownloadStatusCalls() []struct {
	Ctx     context.Context
	VideoID string
	Status  string
} {
	var calls []struct {
		Ctx     context.Context
		VideoID string
		Status  string
	}
	mock.lockSetVideoDownloadStatus.RLock()
	calls = mock.calls.SetVideoDownloadStatus
	mock.lockSetVideoDownloadStatus.RUnlock()
	return calls
}

// SetVideoProgress calls SetVideoProgressFunc.
func (mock *DBMock) SetVideoProgress(ctx context.Context, videoID string, progress int) (*models.Video, error) {
	if mock.SetVideoProgressFunc == nil {
		panic("DBMock.SetVideoProgressFunc: method is nil but DB.SetVideoProgress was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		VideoID  string
		Progress int
	}{
		Ctx:      ctx,
		VideoID:  videoID,
		Progress: progress,
	}
	mock.lockSetVideoProgress.Lock()
	mock.calls.SetVideoProgress = append(mock.calls.SetVideoProgress, callInfo)
	mock.lockSetVideoProgress.Unlock()
	return mock.SetVideoProgressFunc(ctx, videoID, progress)
}

// SetVideoProgressCalls gets all the calls that were made to SetVideoProgress.
// Check the length with:
//
//	len(mockedDB.SetVideoProgressCalls())
func (mock *DBMock) SetVideoProgressCalls() []struct {
	Ctx      context.Context
	VideoID  string
	Progress int
} {
	var calls []struct {
		Ctx      context.Context
		VideoID  string
		Progress int
	}
	mock.lockSetVideoProgress.RLock()
	calls = mock.calls.SetVideoProgress
	mock.lockSetVideoProgress.RUnlock()
	return calls
}

// SetVideoWatchTime calls SetVideoWatchTimeFunc.
func (mock *DBMock) SetVideoWatchTime(ctx context.Context, videoID string, watchTime *time.Time) error {
	if mock.SetVideoWatchTimeFunc == nil {
		panic("DBMock.SetVideoWatchTimeFunc: method is nil but DB.SetVideoWatchTime was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		VideoID   string
		WatchTime *time.Time
	}{
		Ctx:       ctx,
		VideoID:   videoID,
		WatchTime: watchTime,
	}
	mock.lockSetVideoWatchTime.Lock()
	mock.calls.SetVideoWatchTime = append(mock.calls.SetVideoWatchTime, callInfo)
	mock.lockSetVideoWatchTime.Unlock()
	return mock.SetVideoWatchTimeFunc(ctx, videoID, watchTime)
}

// SetVideoWatchTimeCalls gets all the calls that were made to SetVideoWatchTime.
// Check the length with:
//
//	len(mockedDB.SetVideoWatchTimeCalls())
func (mock *DBMock) SetVideoWatchTimeCalls() []struct {
	Ctx       context.Context
	VideoID   string
	WatchTime *time.Time
} {
	var calls []struct {
		Ctx       context.Context
		VideoID   string
		WatchTime *time.Time
	}
	mock.lockSetVideoWatchTime.RLock()
	calls = mock.calls.SetVideoWatchTime
	mock.lockSetVideoWatchTime.RUnlock()
	return calls
}

// SubscribeToChannel calls SubscribeToChannelFunc.
func (mock *DBMock) SubscribeToChannel(ctx context.Context, channel models.Channel) error {
	if mock.SubscribeToChannelFunc == nil {
		panic("DBMock.SubscribeToChannelFunc: method is nil but DB.SubscribeToChannel was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Channel models.Channel
	}{
		Ctx:     ctx,
		Channel: channel,
	}
	mock.lockSubscribeToChannel.Lock()
	mock.calls.SubscribeToChannel = append(mock.calls.SubscribeToChannel, callInfo)
	mock.lockSubscribeToChannel.Unlock()
	return mock.SubscribeToChannelFunc(ctx, channel)
}

// SubscribeToChannelCalls gets all the calls that were made to SubscribeToChannel.
// Check the length with:
//
//	len(mockedDB.SubscribeToChannelCalls())
func (mock *DBMock) SubscribeToChannelCalls() []struct {
	Ctx     context.Context
	Channel models.Channel
} {
	var calls []struct {
		Ctx     context.Context
		Channel models.Channel
	}
	mock.lockSubscribeToChannel.RLock()
	calls = mock.calls.SubscribeToChannel
	mock.lockSubscribeToChannel.RUnlock()
	return calls
}

// UnsubscribeFromChannel calls UnsubscribeFromChannelFunc.
func (mock *DBMock) UnsubscribeFromChannel(ctx context.Context, channelID string) error {
	if mock.UnsubscribeFromChannelFunc == nil {
		panic("DBMock.UnsubscribeFromChannelFunc: method is nil but DB.UnsubscribeFromChannel was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ChannelID string
	}{
		Ctx:       ctx,
		ChannelID: channelID,
	}
	mock.lockUnsubscribeFromChannel.Lock()
	mock.calls.UnsubscribeFromChannel = append(mock.calls.UnsubscribeFromChannel, callInfo)
	mock.lockUnsubscribeFromChannel.Unlock()
	return mock.UnsubscribeFromChannelFunc(ctx, channelID)
}

// UnsubscribeFromChannelCalls gets all the calls that were made to UnsubscribeFromChannel.
// Check the length with:
//
//	len(mockedDB.UnsubscribeFromChannelCalls())
func (mock *DBMock) UnsubscribeFromChannelCalls() []struct {
	Ctx       context.Context
	ChannelID string
} {
	var calls []struct {
		Ctx       context.Context
		ChannelID string
	}
	mock.lockUnsubscribeFromChannel.RLock()
	calls = mock.calls.UnsubscribeFromChannel
	mock.lockUnsubscribeFromChannel.RUnlock()
	return calls
}
