ALTER TABLE videos ADD COLUMN IF NOT EXISTS downloaded_at TIMESTAMP;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS file_path TEXT;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS download_status TEXT;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS download_error TEXT;
