// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package youtube_mock

import (
	"context"
	"github.com/TheEdgeOfRage/ytrssil-api/lib/clients/youtube"
	"github.com/TheEdgeOfRage/ytrssil-api/models"
	"sync"
)

// Ensure, that ClientMock does implement youtube.Client.
// If this is not the case, regenerate this file with moq.
var _ youtube.Client = &ClientMock{}

// ClientMock is a mock implementation of youtube.Client.
//
//	func TestSomethingThatUsesClient(t *testing.T) {
//
//		// make and configure a mocked youtube.Client
//		mockedClient := &ClientMock{
//			GetVideoDurationsFunc: func(ctx context.Context, videos map[string]*models.Video) error {
//				panic("mock out the GetVideoDurations method")
//			},
//			GetVideoMetadataFunc: func(ctx context.Context, videoID string) (*models.Video, error) {
//				panic("mock out the GetVideoMetadata method")
//			},
//		}
//
//		// use mockedClient in code that requires youtube.Client
//		// and then make assertions.
//
//	}
type ClientMock struct {
	// GetVideoDurationsFunc mocks the GetVideoDurations method.
	GetVideoDurationsFunc func(ctx context.Context, videos map[string]*models.Video) error

	// GetVideoMetadataFunc mocks the GetVideoMetadata method.
	GetVideoMetadataFunc func(ctx context.Context, videoID string) (*models.Video, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetVideoDurations holds details about calls to the GetVideoDurations method.
		GetVideoDurations []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Videos is the videos argument value.
			Videos map[string]*models.Video
		}
		// GetVideoMetadata holds details about calls to the GetVideoMetadata method.
		GetVideoMetadata []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// VideoID is the videoID argument value.
			VideoID string
		}
	}
	lockGetVideoDurations sync.RWMutex
	lockGetVideoMetadata  sync.RWMutex
}

// GetVideoDurations calls GetVideoDurationsFunc.
func (mock *ClientMock) GetVideoDurations(ctx context.Context, videos map[string]*models.Video) error {
	if mock.GetVideoDurationsFunc == nil {
		panic("ClientMock.GetVideoDurationsFunc: method is nil but Client.GetVideoDurations was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Videos map[string]*models.Video
	}{
		Ctx:    ctx,
		Videos: videos,
	}
	mock.lockGetVideoDurations.Lock()
	mock.calls.GetVideoDurations = append(mock.calls.GetVideoDurations, callInfo)
	mock.lockGetVideoDurations.Unlock()
	return mock.GetVideoDurationsFunc(ctx, videos)
}

// GetVideoDurationsCalls gets all the calls that were made to GetVideoDurations.
// Check the length with:
//
//	len(mockedClient.GetVideoDurationsCalls())
func (mock *ClientMock) GetVideoDurationsCalls() []struct {
	Ctx    context.Context
	Videos map[string]*models.Video
} {
	var calls []struct {
		Ctx    context.Context
		Videos map[string]*models.Video
	}
	mock.lockGetVideoDurations.RLock()
	calls = mock.calls.GetVideoDurations
	mock.lockGetVideoDurations.RUnlock()
	return calls
}

// GetVideoMetadata calls GetVideoMetadataFunc.
func (mock *ClientMock) GetVideoMetadata(ctx context.Context, videoID string) (*models.Video, error) {
	if mock.GetVideoMetadataFunc == nil {
		panic("ClientMock.GetVideoMetadataFunc: method is nil but Client.GetVideoMetadata was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		VideoID string
	}{
		Ctx:     ctx,
		VideoID: videoID,
	}
	mock.lockGetVideoMetadata.Lock()
	mock.calls.GetVideoMetadata = append(mock.calls.GetVideoMetadata, callInfo)
	mock.lockGetVideoMetadata.Unlock()
	return mock.GetVideoMetadataFunc(ctx, videoID)
}

// GetVideoMetadataCalls gets all the calls that were made to GetVideoMetadata.
// Check the length with:
//
//	len(mockedClient.GetVideoMetadataCalls())
func (mock *ClientMock) GetVideoMetadataCalls() []struct {
	Ctx     context.Context
	VideoID string
} {
	var calls []struct {
		Ctx     context.Context
		VideoID string
	}
	mock.lockGetVideoMetadata.RLock()
	calls = mock.calls.GetVideoMetadata
	mock.lockGetVideoMetadata.RUnlock()
	return calls
}
