// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package parser_mock

import (
	"github.com/TheEdgeOfRage/ytrssil-api/feedparser"
	"sync"
)

// Ensure, that ParserMock does implement feedparser.Parser.
// If this is not the case, regenerate this file with moq.
var _ feedparser.Parser = &ParserMock{}

// ParserMock is a mock implementation of feedparser.Parser.
//
//	func TestSomethingThatUsesParser(t *testing.T) {
//
//		// make and configure a mocked feedparser.Parser
//		mockedParser := &ParserMock{
//			ParseFunc: func(channelID string) (*feedparser.Channel, error) {
//				panic("mock out the Parse method")
//			},
//		}
//
//		// use mockedParser in code that requires feedparser.Parser
//		// and then make assertions.
//
//	}
type ParserMock struct {
	// ParseFunc mocks the Parse method.
	ParseFunc func(channelID string) (*feedparser.Channel, error)

	// calls tracks calls to the methods.
	calls struct {
		// Parse holds details about calls to the Parse method.
		Parse []struct {
			// ChannelID is the channelID argument value.
			ChannelID string
		}
	}
	lockParse sync.RWMutex
}

// Parse calls ParseFunc.
func (mock *ParserMock) Parse(channelID string) (*feedparser.Channel, error) {
	if mock.ParseFunc == nil {
		panic("ParserMock.ParseFunc: method is nil but Parser.Parse was just called")
	}
	callInfo := struct {
		ChannelID string
	}{
		ChannelID: channelID,
	}
	mock.lockParse.Lock()
	mock.calls.Parse = append(mock.calls.Parse, callInfo)
	mock.lockParse.Unlock()
	return mock.ParseFunc(channelID)
}

// ParseCalls gets all the calls that were made to Parse.
// Check the length with:
//
//	len(mockedParser.ParseCalls())
func (mock *ParserMock) ParseCalls() []struct {
	ChannelID string
} {
	var calls []struct {
		ChannelID string
	}
	mock.lockParse.RLock()
	calls = mock.calls.Parse
	mock.lockParse.RUnlock()
	return calls
}
